"""Crear tablas de legalizacion y regimen

Revision ID: 660b746b3805
Revises: a4597b370014
Create Date: 2026-09-01 22:25:23.836517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660b746b3805'
down_revision: Union[str, Sequence[str], None] = 'a4597b370014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regimen_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'managed_by_alembic': True}
    )
    op.create_table('travel_legalizations',
    sa.Column('legalization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('beneficiary', sa.String(length=255), nullable=False),
    sa.Column('nit_beneficiary', sa.String(length=20), nullable=False),
    sa.Column('observations_outlay', sa.Text(), nullable=True),
    sa.Column('regimen_type_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retention_porcentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('retention', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['regimen_type_id'], ['regimen_types.id'], ),
    sa.ForeignKeyConstraint(['travel_request_id'], ['travel_requests.travel_request_id'], ),
    sa.PrimaryKeyConstraint('legalization_id'),
    info={'managed_by_alembic': True}
    )
    
    # Seeder
    regimen_types_table = sa.table('regimen_types',
        sa.column('name', sa.String)
    )
    op.bulk_insert(regimen_types_table, [
        {'name': 'Responsable de IVA'},
        {'name': 'NO Responsable de IVA'},
        {'name': 'Regimen Simple de Tributación'},
        {'name': 'Regimen de tributación especial'}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_legalizations')
    op.drop_table('regimen_types')
    # ### end Alembic commands ###
