"""add includes_food to travel_request

Revision ID: 95558a709af0
Revises: ba03ea7600b5
Create Date: 2026-09-18 02:27:18.904569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95558a709af0'
down_revision: Union[str, Sequence[str], None] = 'ba03ea7600b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_requests', sa.Column('includes_food', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_requests', 'includes_food')
    # ### end Alembic commands ###
